# .streamlit/secrets.toml
[supabase]
url = "https://xwdzexpymvhnvnpeyyoq.supabase.co"
key = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inh3ZHpleHB5bXZobnZucGV5eW9xIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY5OTgyNTAsImV4cCI6MjA3MjU3NDI1MH0.oCyty9Wjiwcq_mE-TsmlZaFc_3LX0DB-A3SZS_2vssI"

[api_keys]
openweather = "bdade00e143b8fc836092c42e933efb7"